# Generated by Django 5.2.7 on 2025-11-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='projects',
            new_name='project',
        ),
    ]
